### ISSUE TITLE
Feature 6 - Add distance ennemy

### ISSUE THREAD

**Issue by lucas-mrq** [hsven/mystic-militia#32]

**Comment by hsven** [comment]
Sorry for commenting, but the title made me worried you'd implement this specifically for enemies.

Creating something like a "distance enemy" is not a enemy-specific thing, but rather a unit type. Along the lines of "infantry", "archers" and so on.
In other words, the affiliation should not matter; unit types should be applicable to either ally or enemy units.

Hope this clears everything up and prevented wasted time!

**Comment by lucas-mrq** [comment]
- [ ] Add arrow persistance if units or enemy died while throwing arrow
